version: "3"
services:
  sillytavern:
    build: ..
    container_name: sillytavern
    hostname: sillytavern
    image: ghcr.io/sillytavern/sillytavern:latest
    ports:
      - "8000:8000"
    volumes:
      - "/root/st/docker/config:/home/node/app/config"
      - "/root/st/docker/data:/home/node/app/data"
      - "/root/st/docker/plugins:/home/node/app/plugins"
    restart: unless-stopped
